/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./components/Themes/DarkModeToggle.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FullScreen: typeof import('./components/Themes/FullScreen.vue')['default']
    Iconify: typeof import('./components/Icon/Iconify.vue')['default']
    IconList: typeof import('./components/Icon/IconList.vue')['default']
    Notice: typeof import('./components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./components/Notice/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/Icon/SvgIcon.vue')['default']
    WebIcon: typeof import('./components/Icon/WebIcon.vue')['default']
  }
}
